# Generated by Django 2.0.3 on 2018-08-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubgHackGoso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shard',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
